### ISSUE TITLE
Configured captchatype is not used by SubmitForm

### ISSUE THREAD

**Issue by Pkiri** [joomdev/JD-Simple-Contact-Form#12]
When you configure a different Captcha in JD Simple Contact form, then the one that is configured in Joomla Global, captcha does not work. 

**Steps to reproduce**
Install at least two captcha components
Configure Captcha in Joomla Global to captcha component 1 (for example "Captcha - Aimy Captcha-Less Form Guard")
Configure in JS Simple Contact Form the second captcha component (for example Recaptcha)

When you try to fill the form and submit, you get errors. 

The problem seems to be that in SubmitForm a different selection is used for the captcha:
_$captchaType = JFactory::getApplication()->get('captcha');_

Can this be fixed?

**Comment by actuallyakash** [comment]
@Pkiri,

Let me test the issues and I'll get back to you.

**Comment by actuallyakash** [comment]
HI @Pkiri,

Thank you for your patience.

This has been resolved in 03b02ef1a629dda795e4c4bcb26b78ab812f894c.

Closing the issue then.
