### ISSUE TITLE
Joomla 4 Compatibility!

### ISSUE THREAD

**Issue by chetanmadaan** [joomdev/JD-Simple-Contact-Form#13]
@actuallyakash Is this something that we can work on?

This should help:
https://github.com/vortrixs/joomla-namespace-checker

I can help with testing if needed!

**Comment by actuallyakash** [comment]
Yes, we can try this out. PHP is also going to release v8.

It'll be useful. I don't think it's needed at the moment. We should wait until both of Joomla and PHP versions are out for tests.

**Comment by chetanmadaan** [comment]
Well, we'll be up for a race once they are out. But sure, we can wait.
