### ISSUE TITLE
Recaptcha not showing

### ISSUE THREAD

**Issue by robwent** [joomdev/JD-Simple-Contact-Form#4]
Hi,

I've enabled the captcha option in the module.

I added keys to the core invisible recaptcha plugin and set that as the default in global config.

On the page with the module, I can see the recaptcha scripts loding in the head of the page, but there is no recaptcha logo showing on the page and it doesn't seem to work.

I couldn't see any other options for recaptcha other than turning it on.

Have I missed something or is this a core config issue?

**Comment by robwent** [comment]
I just tried with v2 and v3 keys.

When I check the network tab on submit, I see an error returned:

`{"status":"error","code":0,"message":"Empty solution not allowed.","line":152,"file":"domain\\plugins\\captcha\\recaptcha_invisible\\recaptcha_invisible.php"}`

**Comment by actuallyakash** [comment]
Hello @robwent,

You've to enable **CAPTCHA - reCAPTCHA** instead of **CAPTCHA - Invisible reCAPTCHA** in your **plugins menu**.

**Note**: Keep the Invisible reCaptcha disabled when reCaptcha is enabled to avoid conflicts.

**Comment by robwent** [comment]
Hi,

Do you have any plans to support invisible recaptcha in the future?

**Comment by actuallyakash** [comment]
Hey @robwent,
Let me check with the team and will be updating you soon!

**Comment by chetanmadaan** [comment]
@robwent we do have plans to support all Joomla "Captcha" plugins. Not just the system one's but any 3rd party one's as well.

It should come up before the end of the month. we will post back here once we have an update.

Thanks,
Chetan

**Comment by robwent** [comment]
That's great news!

I've got the checkbox working so will close this.
