### ISSUE TITLE
Error sending the form

### ISSUE THREAD

**Issue by marco-zan** [joomdev/JD-Simple-Contact-Form#5]
Submitting the form with ajax i get this error:
{"status":"error","code":0,"message":"[]","line":271,"file":"W:\\xampp72\\htdocs\\modules\\mod_jdsimplecontactform\\helper.php"}

or, when i try submitting without ajax, it sends me an error "Error while sending email"

**Comment by chetanmadaan** [comment]
Hello,

Are other emails on your Joomla site working? Can you test the config and other emails are going out of the site fine?

Thanks,
Chetan

**Comment by marco-zan** [comment]
No I can't send mail using any form add-on, even the one included with the template. I will fix them first. But any suggestions?

**Comment by chetanmadaan** [comment]
Contact your web hosting to see if they can help.
