### ISSUE TITLE
Does not work without (session) cookies

### ISSUE THREAD

**Issue by gruenkaeppchen** [joomdev/JD-Simple-Contact-Form#6]
**Problem:**
when the user does not accept cookies the form will redirect to _my-domain.com_/component/ajax/ and it will fail with the following error message:

> InvalidArgumentException: Please specify a valid response format, other
than that of HTML, such as json, raw, debug, etc.

**Solution:**
no solution available as the form will not work without cookies

**Suggestion:**
- the submit button should not be clickable if cookies are not accepted
- the user should be informed about not being able to use the form without cookies

**Comment by chetanmadaan** [comment]
Hello,

Are you using a particular module/extension for prompting user for cookies?

Thanks,
Chetan

**Comment by gruenkaeppchen** [comment]
No. The website has been purely informational (no login etc.). So far no cookies were needed to be able to fully use/access the website.
Now I have installed JD-Simple-Contact-Form and users get the error message mentioned above after submitting their data when they do not accept cookies.

**Comment by chetanmadaan** [comment]
Got it. Is it possible to get a link to your website?

Thanks,
Chetan

**Comment by gruenkaeppchen** [comment]
Sure, just try it in this new sandbox:
https://jdtest.joomla.com/index.php/jd-simple-form-test

**Comment by chetanmadaan** [comment]
Hello,

I opened the link in private browsing. didn't accepted cookies in Joomla  (_wasn't prompted to_) and was able to submit it just fine.

Thanks,
Chetan

**Comment by gruenkaeppchen** [comment]
Well, private browsing alone won't do as firefox still accepts cookies but will delete these after you close your browser:

[https://support.mozilla.org/en-US/kb/private-browsing-use-firefox-without-history](url)

> Private Browsing automatically erases your browsing information, such as passwords, cookies and history, leaving no trace after you end the session.

> Cookies set in private windows are held temporarily in memory, separate from regular window cookies, and discarded at the end of your private session (after the last private window is closed). 

Using the default settings firefox won't ask you to accept cookies.
So you will have to go the firefox's preferences and block cookies.
`Firefox -> Preferences -> Privacy & Security -> Content Blocking -> Custom -> Cookies -> All Cookies`

Or you can just manually delete the website cookies before hitting the submit button:
`Firefox -> Preferences -> Privacy & Security -> Content Blocking -> Cookies and Site Data -> Manage Data`
search for 'jdtest.joomla.com', select the cookie (should only be one), hit "Remove selected" and "Save changes" and confirm.
All cookies are gone now and if you hit the submit button now (without reloading the page of course, otherwise the cookie will be re-set by Joomla!) you will get the error message shown on the webpage.
Same thing happens if your browser does not accept cookies.

**Comment by actuallyakash** [comment]
@gruenkaeppchen Thanks for pointing this out and for the suggestion.
JDSCF does need cookies to be submitted. We will be rolling the JDSCF with a new update containing **No cookies enabled notice**.

**Comment by actuallyakash** [comment]
Done in 2b5414625d6feaf967b75bb1604b8d84ece29cd4
