### ISSUE TITLE
Include IP address in the default email template?

### ISSUE THREAD

**Issue by chetanmadaan** [joomdev/JD-Simple-Contact-Form#7]
Possible to do that?

By default the option can be disabled.
If enabled, It would include the IP in the email template as the last field.

IP address: xxx.xx.xx.xx and it can be hyperlinked to whois.domaintools.com/{xx.xx.xx.xxx} for quick whois lookup.

No Rush!!

**Comment by actuallyakash** [comment]
Yes, totally possible.

**Comment by chetanmadaan** [comment]
done in https://github.com/joomdev/JD-Simple-Contact-Form/commit/116028e222ac1f6cdfacfcbfcf9d02e53ad63fbf
