### ISSUE TITLE
Error 'File size is too big!' on empty form

### ISSUE THREAD

**Issue by felicjan** [joomdev/JD-Simple-Contact-Form#8]
Hi, I get an error 'File size is too big!' already on empty form. The error does not disappear even if I choose an attachment.

Joomla! 3.9.14 Stable

**Comment by chetanmadaan** [comment]
Can you provide a link to your website?

**Comment by actuallyakash** [comment]
Not able to reproduce the issue.
Closing.  You can open it again anytime.
